project:
  title: "BD-sschool-2025-web"
  type: website

lang: es

format:
  html:
    theme:
      - sandstone
      - 00_assets/styles/main.scss
    highlight: tango
    grid:
      sidebar-width: 100px
      body-width: 950px


# Font/colors -------------------------
fontsize: 12pt
citecolor: purple
toccolor: teal
linkcolor: teal
urlcolor: magenta
backgroundcolor: '#FFF8F0'

# Figures and tables ------------------
fig-align: 'center'
fig-pos: 'bt!'
fig-cap-location: 'bottom'
tbl-cap-location: 'top'
lightbox: true

# Cross-references --------------------
crossref:
  fig-title: "Fig."
  fig-prefix: "Fig."
  title-delim: "."

# Code --------------------------------
execute:
  echo: false
  warning: false

# Format ---------------------------
keep-tex: false
geometry:
  - margin = 1in
  - heightrounded
linestretch: 1.5
anchor-sections: true
smooth-scroll: true
section-divs: true

## TOC + sections --------------------
toc: true
toc-title: "Contenidos"
toc-depth: 2
number-depth: 2
toc-location: right
number-sections: true
