project:
  title: "BD-sschool-2025-web"

lang: es

format:
  html:
    theme: sandstone
    highlight: tango
    css: 00_assets/styles/styles.css

# Font -------------------------------
fontsize: 12pt
citecolor: purple
toccolor: teal
linkcolor: teal
urlcolor: magenta

# Figures and tables ------------------
fig-align: 'center'
fig-pos: 'bt!'
fig-cap-location: 'bottom'
tbl-cap-location: 'top'

# Cross-references --------------------
crossref:
  fig-title: "Fig."
  fig-prefix: "Fig."
  title-delim: "."

# Code --------------------------------
execute:
  echo: false
  warning: false

# Format ---------------------------
keep-tex: false
geometry:
  - margin = 1in
  - heightrounded
linestretch: 1.5
number-sections: true
toc: true
toc-depth: 3
toc-location: right
