
```{r}
#| include: false
library(dplyr)
library(mapgl)
library(sf)
```


::::::::::: mapcard
:::::::::: grid
::::::::: {.g-col-12 .g-col-lg-6}
::: mapcard__title
Te interesa?
:::

:::::: grid
::: {.g-col-4 .mapcard__opts}
Fechas:

Organiza:

Localización:

Idioma:

Créditos:

Precio:
:::

::: {.g-col-8 .mapcard__answ}
23 junio - 25 junio 2025

Universidad de Córdoba

Córdoba, España

Español

5 ECTS

67,75€
:::

::: {.g-col-12 .mapcard__btn .btn onclick="window.open('https://hdzvlf-adrian-cidre0gonz0lez.shinyapps.io/preinscripcion-summer-school/', '_blank')"}
Preinscripción {{< fa arrow-up-right-from-square >}}
:::

::::::

:::::::::

::: {.g-col-12 .g-col-lg-6 .mapcard__map}
```{r}
rabanales_sf <- st_point(c(-4.724533, 37.915041)) |> 
  st_sfc(crs = 4326) |> 
  st_as_sf() |> 
  mutate(Edificio = "Edificio Da Vinci")

maplibre() |> 
  fly_to(
    center = c(-4.724533, 37.915041),
    zoom = 3
  ) |>
  add_markers(
    data  = rabanales_sf
  ) |>
  add_navigation_control()
```
:::
::::::::::
:::::::::::
